Combine fetch() and json()
wikimedia/wvui pull request #82
Opened 2020-09-01 02:32 UTC by berndsi

Combine fetch() and json() so it can be easily replaced by another implementation, like jQuery.ajax().
Add optional parameter to the SearchClient so a client can pass in an alternative getJson() implementation.
If none is provided then native fetch is used.

2020-09-01 14:01 UTC, niedzielski commented on src/components/typeahead-search/http/SearchClient.ts
> +		fetchJsonImpl?: GetJson
Any reason not to request the fetch implementation in the search implementation constructor instead?

2020-09-01 14:02 UTC, niedzielski commented on src/components/typeahead-search/http/SearchClient.ts
> +	 * @param fetchJsonImpl a function which returns a promise that resolves to a json
Nitpick: casing on "json" should be upper.

2020-09-01 14:04 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +		fetchByTitle( query, domain, limit = 10, getJsonImpl = undefined ) {
Here we default to undefined but above we default to fetchJson. Is it possible to stick to one or the other?

2020-09-01 14:08 UTC, niedzielski commented on src/http/fetch.ts
>  	if ( 'fetch' in window ) {
Do you think this check still makes sense? If the client doesn't specify a Fetch implementation they're implicitly saying that window.fetch is available.

2020-09-01 14:09 UTC, niedzielski commented on src/http/fetch.ts
> +					return {};
Should we reject here? If not, please consider adding a comment inline.

2020-09-01 14:11 UTC, niedzielski commented on src/http/fetch.ts
> +export type GetJson = (
Would "FetchJson"  naming improve the parity with the fetchJson implementation below?

2020-09-01 14:13 UTC, niedzielski commented on src/http/fetch.ts
> +// The plan is to add a way for clients of this library to pass in an implementation, e.g.
We can probably describe the intended operation as it is now since we're building what we need for today.

2020-09-01 14:15 UTC, niedzielski commented on src/http/fetch.ts
> +) => Promise<Record<string, unknown>>;
Does this always return a record? I would guess that we can only assume a JSON type here.

2020-09-01 14:19 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +	const restResponse: RestResponse = response as unknown as RestResponse;
Should we reject the outer Promise if a bad type is passed in?

2020-09-01 15:08 UTC, berndsi commented on src/http/fetch.ts
> +) => Promise<Record<string, unknown>>;
@niedzielski I really want a JSON object here, so I tried `object`, which lint is unhappy with:
> Don't use `object` as a type. The `object` type is currently hard to use ([see this issue](https://github.com/microsoft/TypeScript/issues/21732)).
Consider using `Record<string, unknown>` instead, as it allows you to more easily inspect and use the keys  @typescript-eslint/ban-types

Trying `Object` lead me to this:
> Don't use `Object` as a type. The `Object` type actually means "any non-nullish value", so it is marginally better than `unknown`.
- If you want a type meaning "any object", you probably want `Record<string, unknown>` instead.
- If you want a type meaning "any value", you probably want `unknown` instead  @typescript-eslint/ban-types

2020-09-01 15:31 UTC, niedzielski commented on src/http/fetch.ts
> +) => Promise<Record<string, unknown>>;
It's my understanding that TypeScript's `object` won't cover all valid JSON types like `null`, just like `Record`. If the response might be `null` or any non-object type, neither `Record` nor `object` seems like a good choice. Maybe `unknown` is the best we can do for now.

https://www.typescriptlang.org/docs/handbook/basic-types.html#object
https://www.json.org
https://github.com/microsoft/TypeScript/issues/1897

2020-09-01 16:26 UTC, berndsi commented on src/components/typeahead-search/http/SearchClient.ts
> +		fetchJsonImpl?: GetJson
Good suggestion. I've moved it to become a parameter of the search implementation constructor.

2020-09-01 19:35 UTC, berndsi commented on src/components/typeahead-search/http/SearchClient.ts
> +	 * @param fetchJsonImpl a function which returns a promise that resolves to a json
That code got removed. I've updated the other occurrence of this.

2020-09-01 19:35 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +		fetchByTitle( query, domain, limit = 10, getJsonImpl = undefined ) {
Excellent idea. That simplifies some of the code.

2020-09-01 19:35 UTC, berndsi commented on src/http/fetch.ts
>  	if ( 'fetch' in window ) {
I've taken it out.

2020-09-01 19:35 UTC, berndsi commented on src/http/fetch.ts
> +					return {};
Sounds good.

2020-09-01 19:35 UTC, berndsi commented on src/http/fetch.ts
> +// The plan is to add a way for clients of this library to pass in an implementation, e.g.
Done.

2020-09-01 19:40 UTC, berndsi commented on src/http/fetch.ts
> +export type GetJson = (
FetchJson sounds good to me. The drawback would be that it's the same as fetchJson if you ignore the former starting with an uppercase letter. What do you think about renaming `fetchJson` to `nativeFetchJson`?

2020-09-01 20:49 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +	const restResponse: RestResponse = response as unknown as RestResponse;
Do you mean with the `if ( !( 'pages' in response ) )` I had above?

2020-09-01 21:10 UTC, niedzielski commented on src/http/fetch.ts
> +			} else {
Very minor: the else here is optional given the return statement on the line above.

2020-09-01 21:14 UTC, niedzielski commented on src/http/fetch.ts
> +export type GetJson = (
Personally, I like `FetchJson` with the thinking that PascalCase signals types and cameCase signals instances. Not a big deal either way.

2020-09-01 21:16 UTC, niedzielski commented on src/http/fetch.ts
> +export function fetchJson(
It occurs to me that we will probably want the ability to cancel requests. How do you think we should represent that? In Popups, we [added a method to the Promise object](https://gerrit.wikimedia.org/g/mediawiki/extensions/Popups/+/master/src/gateway/rest.js#77) but I'm not sure if that's a good idea or not here.

2020-09-01 21:23 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +	const restResponse: RestResponse = response as unknown as RestResponse;
What I mean is that it felt a little strange to say that we expect a generic parameter, and then we test that parameter for the pages property, and then we still cast it here. Personally, I normally use [type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates) which are usually imperfect but at least capture the idea without a cast. There's at least one example in [WVUI's InputType](https://github.com/wikimedia/wvui/blob/master/src/components/input/InputType.ts#L13).

2020-09-01 21:24 UTC, berndsi commented on src/http/fetch.ts
> +) => Promise<Record<string, unknown>>;
@niedzielski Ok, switching from Record<string, unknown> to unknown looks simpler.

2020-09-01 21:40 UTC, berndsi commented on src/http/fetch.ts
> +export type GetJson = (
Done

2020-09-01 21:41 UTC, berndsi commented on src/http/fetch.ts
> +					return {};
Done

2020-09-01 21:55 UTC, berndsi commented on src/http/fetch.ts
> +export function fetchJson(
This requires some more thought. Can this be done in a separate PR?

2020-09-01 22:53 UTC, berndsi commented on src/http/fetch.ts
> +			} else {
Replaced it with a guard clause.

2020-09-02 13:05 UTC, speedandfunction-anribolon commented on src/http/fetch.ts
> +export function fetchJson(
Just for the reference, it will require adding 2 different implementations. $.getJson() returns a promise with jqXHR object, which has `abort()` method (as @niedzielski mentioned above). `fetch` implementation will require using [AbortController](https://developer.mozilla.org/ru/docs/Web/API/AbortController). I think it's a good idea to split it to a separate patch @niedzielski @berndsi

2020-09-02 13:07 UTC, speedandfunction-anribolon reviewed
LGTM! Just a small comment inline.

2020-09-02 13:07 UTC, speedandfunction-anribolon commented on src/components/typeahead-search/http/restSearchClient.ts
> +			if ( !query ) {
Minor: Consider adding extra line before `if` statement, It's a good practice.

2020-09-02 16:00 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +	const restResponse: RestResponse = response as unknown as RestResponse;
@niedzielski I've pushed my first attempt. It currently still feels a bit weird since it also involves a cast:
```
function isRestResponse( response: unknown ): response is RestResponse {
	return ( response as RestResponse ).pages !== undefined;
}
```

I've tried something like this:
```
function isRestResponse( response: unknown ): response is RestResponse {
	return 'pages' in response;
}
```
but that results in `TS2571: Object is of type 'unknown'`.

2020-09-02 17:25 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +			if ( !query ) {
I've added one before and after. IMO the one afterwards is more important since the if block includes a return statement.

2020-09-02 17:29 UTC, berndsi commented on src/http/fetch.ts
> +export function fetchJson(
Yes, the other reason is that we need to look at the browser compatibility table of [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility). AbortController is marked as experimental.

2020-09-02 19:06 UTC, niedzielski commented on src/http/fetch.ts
> +export function fetchJson(
Let's explore in a new PR :+1: Maybe we can abort when available (either AbortController or XHR / jQuery-based) and reject the promise otherwise.

2020-09-02 19:28 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
I think you can avoid the case with something like this:

```ts
function isRestResponse( response: unknown ): response is RestResponse {
  return response instanceof Object && 'pages' in response && Array.isArray( response['pages'] )
}
```

2020-09-02 19:54 UTC, niedzielski requested changes
Looking good. Just a couple more notes inline but you're close to the finish line from my perspective :+1:

2020-09-02 19:54 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +	return Promise.resolve( response as RestResponse );
Do we need this case here? The type guard is supposed to infer the type.

2020-09-02 19:54 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +		return Promise.reject( 'Not a valid RestResponse' );
Extremely minor: consider rewording to the terser "Invalid RestResponse."

2020-09-02 19:54 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +				limit: limit
Consider shorthand for limit: `{q: query, limit }`.

2020-09-02 20:05 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
Our eslint rules don't like `Array.isArray( response[ 'pages' ] )`:
```
 ["pages"] is better written in dot notation  dot-notation
```

2020-09-02 20:10 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
Maybe use a line disable? Generally, that lint is a valid style criticism but TypeScript only recognizes the indexing syntax for this scenario.

2020-09-02 20:14 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +	return Promise.resolve( response as RestResponse );
Good call. Removed the cast.

2020-09-02 20:14 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +		return Promise.reject( 'Not a valid RestResponse' );
Done

2020-09-02 20:16 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +				limit: limit
Done. Good catch!

2020-09-02 20:18 UTC, speedandfunction-anribolon commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
Please correct me if I'm wrong, but I think we should stand at the point where we know what exactly rest api returns. This is not that kind of rest Api Client that is considered to be a part of the library.

2020-09-02 20:22 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
I suppose that's fair. An API is a contract so hopefully the MediaWiki REST folks will adhere to it. Soo... Cast I guess?

2020-09-02 20:39 UTC, speedandfunction-anribolon commented on src/components/typeahead-search/http/restSearchClient.ts
>  	};
I think it might be simplified a bit:
```
restResponse.pages
				.map( ( {thumbnail, ...theRestOfPage} ) => ( {
					...theRestOfPage
					thumbnail: thumbnail ? {
						url: thumbnail.url,
						width: thumbnail.width ?? undefined,
						height: thumbnail.height ?? undefined
					} : undefined
				} ) )
```

2020-09-02 20:43 UTC, speedandfunction-anribolon commented on src/components/typeahead-search/http/restSearchClient.ts
>  	};
Or just for to be more precise
restResponse.pages
				.map( ( {thumbnail, id, key, title, description} ) => ( {
					id,
                                        key,
                                        title,
                                        description,
					thumbnail: thumbnail ? {
						url: thumbnail.url,
						width: thumbnail.width ?? undefined,
						height: thumbnail.height ?? undefined
					} : undefined
				} ) )

2020-09-02 21:38 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
>  	};
LGTM.

2020-09-02 21:40 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
Are you saying I should remove some of these checks or leave as is?

2020-09-02 23:19 UTC, niedzielski commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
I'm saying to drop this function and sorry for my poor direction :]

@speedandfunction-anribolon is right. If this function's purpose is to check that the API is valid, it's not a real API because they're not adhering to the contract. If that's the case, we can leave this code in but should file a bug report. If that's not the case, we should be able to just cast from unknown to RestResponse without any checks.

2020-09-03 15:18 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
> +function isRestResponse( response: unknown ): response is RestResponse {
@niedzielski @speedandfunction-anribolon Ok, I've removed this code now. It's back to just the cast, as it was before

2020-09-03 15:18 UTC, berndsi commented on src/components/typeahead-search/http/restSearchClient.ts
>  	};
I made that change yesterday.

2020-09-03 15:37 UTC, merged