Blubber Config + Docker setup
wikimedia/wvui pull request #86
Opened 2020-09-03 18:06 UTC by nikkhn

This is an initial go at a blubber config and docker-compose setup. I am by no means an expert so feel free to poke/pry. I also removed a few things that I believe are taken care of by eslint-config-wikimedia npm module.

2020-09-03 18:38 UTC, niedzielski commented
@nikkhn, I'm guessing it's ok to reopen this.

2020-09-03 18:44 UTC, nikkhn commented
@niedzielski I actually think I will just cherry-pick my commits into the gerrit repo like you suggested today. (Was trying to be slightly lazy and just keep this branch open and merge it in github haha)

2020-09-03 18:44 UTC, closed without merging

2020-09-03 18:48 UTC, niedzielski requested changes

2020-09-03 18:48 UTC, niedzielski commented on .stylelintignore
> +Dockerfile
Would you mind using an anchored path for the Dockerfile? `/Dockerfile`. It's definitely not a big deal but the rationale is that we've been erring on side of precision in trying to keep our ignore files very intentional and specific.

2020-09-03 18:48 UTC, niedzielski commented on Dockerfile
> +RUN npm install
Is this the recommended command from RelEng / WMDE or should we use `npm ci`?

2020-09-03 18:48 UTC, niedzielski commented on .pipeline/blubber.yaml
> +version: v4
Please add a new section to the readme for Docker. The section should cover at least what Docker is used for in this repo and how to maintain it. For example, if adding a dependency now requires rebuiding the Docker image each time, the readme should cover that. If Docker is optional for local development, which I believe it is, the section should explicit call that out.

2020-09-03 18:48 UTC, niedzielski commented on .pipeline/blubber.yaml
> +            command: [npm, build]
Does this line run `npm build` or `npm run build`? I thought we wanted the latter but could be mistaken.

2020-09-03 18:48 UTC, niedzielski commented on package.json
> -    "linter:js": "eslint --cache --max-warnings 0 --report-unused-disable-directives --ext .js,.json,.ts,.vue",
Can you tell me what this change is for?

2020-09-03 18:48 UTC, niedzielski commented on package-lock.json
>          "del": "^4.1.1"
From what I see, there are no changes to dependencies in this PR so this file should not be changed.

2020-09-03 18:48 UTC, niedzielski commented on docker-compose.yaml
> +            - "3003:3003"
Is this to match Storybook? If so, please add a comment.

2020-09-03 18:48 UTC, niedzielski commented
@nikkhn, just saw your comment. Works for me :+1:

2020-09-04 14:41 UTC, nikkhn commented
@niedzielski I will copy over your pr comments to gerrit and address there so they are documented